version: '3.2'

services:

  rabbitmq:
    container_name: some-rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    links: 
      - create_user
      - list_user
    extra_hosts:
      flaskapp: 10.128.0.5

  create_user:
    container_name: create-user
    build: create_user/
    ports:
      - "5000:5000"
    links: 
      - rabbitmq
      
  data_service:
    container_name: data-service
    build: data_service/
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
      - mongodb 
 
  list_user:
    container_name: list-user
    build: list_user/
    ports:    
      - "5001:5001"
    depends_on:
      - mongodb2
    links: 
      - mongodb2
      
  mongodb:
    container_name: insert-mongodb
    image: mongo
    command: mongod --replSet my-mongo-set
    volumes:
      - "./db:/data/db"
    ports:
      - 27017:27017

  mongodb2:
    container_name: query-mongodb
    image: mongo
    command: mongod --replSet my-mongo-set
    volumes:
      - "./db:/data/db2"
    ports:
      - 27018:27017
networks:
   my-mongo-cluster:
  

